/**
 * Copyright (c) 2020 University of Luxembourg. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be
 * used to endorse or promote products derived from this software without specific prior
 * written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE UNIVERSITY OF LUXEMBOURG AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE UNIVERSITY OF LUXEMBOURG OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

/*  
   NEXMark Generator -- Niagara Extension to XMark Data Generator

   Acknowledgements:
   The NEXMark Generator was developed using the xmlgen generator 
   from the XMark Benchmark project as a basis. The NEXMark
   generator generates streams of auction elements (bids, items
   for auctions, persons) as opposed to the auction files
   generated by xmlgen.  xmlgen was developed by Florian Waas.
   See http://www.xml-benchmark.org for information.

   Copyright (c) Dept. of  Computer Science & Engineering,
   OGI School of Science & Engineering, OHSU. All Rights Reserved.

   Permission to use, copy, modify, and distribute this software and
   its documentation is hereby granted, provided that both the
   copyright notice and this permission notice appear in all copies
   of the software, derivative works or modified versions, and any
   portions thereof, and that both notices appear in supporting
   documentation.

   THE AUTHORS AND THE DEPT. OF COMPUTER SCIENCE & ENGINEERING 
   AT OHSU ALLOW USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION, 
   AND THEY DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES 
   WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.

   This software was developed with support from NSF ITR award
   IIS0086002 and from DARPA through NAVY/SPAWAR 
   Contract No. N66001-99-1-8098.

*/


/*
 * EventCollector.cpp
 *
 *  Created on: April 2, 2020
 *      Author: damien.tassetti
 */

#include "EventCollector.hpp"
#include "PODTypes.hpp"

#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <iomanip> // setprecision
#include <mpi.h>


using nexmark_gen::EventCollector;
using nexmark_gen::Event;

EventCollector::EventCollector(int tag, int rank, int worldSize) :
		Vertex(tag, rank, worldSize) {
	pthread_mutex_init(&mutex, NULL);
}

EventCollector::~EventCollector() {
}

void EventCollector::batchProcess() {
}

void EventCollector::streamProcess(int channel) {

	// read all ranks
	// if (rank == 0) {

		Message* inMessage;
		list<Message*>* tmpMessages = new list<Message*>();

		while (ALIVE) {

			pthread_mutex_lock(&listenerMutexes[channel]);

			while (inMessages[channel].empty())
				pthread_cond_wait(&listenerCondVars[channel],
						&listenerMutexes[channel]);

			while (!inMessages[channel].empty()) {
				inMessage = inMessages[channel].front();
				inMessages[channel].pop_front();
				tmpMessages->push_back(inMessage);
			}

			pthread_mutex_unlock(&listenerMutexes[channel]);

			while (!tmpMessages->empty()) {

				inMessage = tmpMessages->front();
				tmpMessages->pop_front();

				pthread_mutex_lock(&mutex); // to get a nice display
				debug(inMessage);
				pthread_mutex_unlock(&mutex);

				delete inMessage; // delete message from incoming queue
			}

			tmpMessages->clear();
		}

		delete tmpMessages;
	// }
}

void EventCollector::debug(Message*const message){
	// do not delete the message here
	int message_id = Serialization::unwrap<int>(message);
	int nof_events = message->size / sizeof(Event);
	int nof_errors = 0;
	int nof_bids = 0;
	int nof_auctions = 0;
	int nof_persons = 0;
	for(size_t i = 0; i < nof_events ; i++){
		const Event& e = Serialization::read_front<Event>(message, sizeof(Event) * i);
		switch (e.event_type)
		{
		case BidType:
			nof_bids++;
			break;
		
		case AuctionType:
			nof_auctions++;
			break;

		case PersonType:
			nof_persons++;
			break;
			
		default:
			nof_errors++;
			break;
		}
	}
	cout << setprecision(5) << MPI_Wtime();
	cout << setprecision(4);
	cout << "#" << message_id << " NOF_EVENTS: " << nof_events << "\n";
	cout << "\t errors: " << nof_errors << "\n";
	cout << "\t bids: " << 100.0 * nof_bids / nof_events << "% (" << nof_bids << ")\n";
	cout << "\t auctions: " << 100.0 * nof_auctions / nof_events << "% (" << nof_auctions << ")\n";
	cout << "\t nof_persons: " << 100.0 * nof_persons / nof_events << "% (" << nof_persons << ")\n" << endl;
}