/**
 * Copyright (c) 2020 University of Luxembourg. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be
 * used to endorse or promote products derived from this software without specific prior
 * written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE UNIVERSITY OF LUXEMBOURG AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE UNIVERSITY OF LUXEMBOURG OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

/*  
   NEXMark Generator -- Niagara Extension to XMark Data Generator

   Acknowledgements:
   The NEXMark Generator was developed using the xmlgen generator 
   from the XMark Benchmark project as a basis. The NEXMark
   generator generates streams of auction elements (bids, items
   for auctions, persons) as opposed to the auction files
   generated by xmlgen.  xmlgen was developed by Florian Waas.
   See http://www.xml-benchmark.org for information.

   Copyright (c) Dept. of  Computer Science & Engineering,
   OGI School of Science & Engineering, OHSU. All Rights Reserved.

   Permission to use, copy, modify, and distribute this software and
   its documentation is hereby granted, provided that both the
   copyright notice and this permission notice appear in all copies
   of the software, derivative works or modified versions, and any
   portions thereof, and that both notices appear in supporting
   documentation.

   THE AUTHORS AND THE DEPT. OF COMPUTER SCIENCE & ENGINEERING 
   AT OHSU ALLOW USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION, 
   AND THEY DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES 
   WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.

   This software was developed with support from NSF ITR award
   IIS0086002 and from DARPA through NAVY/SPAWAR 
   Contract No. N66001-99-1-8098.

*/


/*
 * Persons.cpp
 *
 *  Created on: April 2, 2020
 *      Author: damien.tassetti
 */

#include "Persons.hpp"
#include "Random.hpp"
#include "FirstNames.hpp"
#include "LastNames.hpp"
#include "States.hpp"
#include "Cities.hpp"
#include "Emails.hpp"
#include "Educations.hpp"

#include <iostream>

using nexmark_gen::PersonsManager;
using std::string;
using std::to_string;
using std::cout;
using std::endl;

PersonsManager::PersonsManager(int worldSize, int rank) :
   worldSize(worldSize),
   rank(rank) {
   this->nof_persons = 0;
   // cout << lastnames_maxlength << endl; // 16
   // cout << firstnames_maxlength << endl; // 17
   // cout << extensions_maxlength << endl; // 24
   // cout << educations_maxlength << endl; // 15
   // cout << cities_maxlength << endl; // 15
   // cout << states_maxlength << endl; // 30
}

int PersonsManager::getExistingId() {
   if (nof_persons == 0) {
      std::cerr << "There is no existing person\n";
      throw "There is no existing person";
   } else {
      return Random::getRandomInt(0, nof_persons - 1) * worldSize + rank;
   }
}

int PersonsManager::getNewId() {
   int new_id = nof_persons * worldSize + rank;
   nof_persons++;
   return new_id;
}

string PersonsManager::getFirstName(){
   return first_names[Random::getRandomInt(0, first_names.size()-1)];
}

string PersonsManager::getLastName(){
   return last_names[Random::getRandomInt(0, last_names.size()-1)];
}

string PersonsManager::getEmailExtension(){
   return email_extensions[Random::getRandomInt(0, email_extensions.size()-1)];
}

string PersonsManager::getRandomStreet(){
   return to_string(Random::getRandomInt(1, 99)) + " " + getLastName() + " St";
}

string PersonsManager::getRandomState(){
   const string random_state = states[Random::getRandomInt(0, states.size()-1)];
   return random_state;
}

string PersonsManager::getRandomCity(){
   const string random_city = cities[Random::getRandomInt(0, cities.size()-1)];
   return random_city;
}

int PersonsManager::getRandomZipCode(){
   return Random::getRandomInt(1, 99999);
}

string PersonsManager::getRandomPhoneNumber(){
   const string phone_number = "+" + to_string(Random::getRandomInt(1, 98)) + "(" + to_string(Random::getRandomInt(10, 998)) + ")" + to_string(Random::getRandomInt(123457, 9987652));
   return phone_number;
}

string PersonsManager::getRandomCreditcard(){
   return to_string(Random::getRandomInt(1000, 9999)) + " " + to_string(Random::getRandomInt(1000, 9999)) + " " + to_string(Random::getRandomInt(1000, 9999)) + " " + to_string(Random::getRandomInt(1000, 9999));
}

double PersonsManager::getRandomIncome(){
   return (double)Random::getRandomInt(40000,70000) + (double)Random::getRandomInt(0,99) / 100;
}

string PersonsManager::getRandomEducation(){
   return educations[Random::getRandomInt(0, educations.size()-1)];
}

string PersonsManager::getRandomGender(){
   vector<string> genders = {"male", "female"}; 
   return genders[Random::getRandomInt(0, 1)];
}

int PersonsManager::getRandomAge(){
   return Random::getRandomInt(30, 44);
}
